export const    CardActionTypes = {
    TOOGLE_CART_HIDDEN:'TOOGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    REMOVE_ITEM_TO_CHART:'REMOVE_ITEM_TO_CHART',
    CLEAR_ITEM_FROM_CART:'CLEAR_ITEM_FROM_CART',
    CLEAR_CART:'CLEAR_CART'
}

export const AuthActionsTypes = {
    SET_CURRENT_USER:'SET_CURRENT_USER',
    CHECK_USER_SESSION:'CHECK_USER_SESSION',
    SIGN_OUT:'SIGN_OUT_START',
}
